import Foundation

enum MapGenerator {
    static func markdown(_ config: Config) -> String {
        var out = "# Soundboard layer map\n\n"
        out += "Every key in the Dygma soundboard layer sends **Hyper (⌃⌥⇧⌘) + key**. "
        out += "In Bazecor, assign the physical key to the same letter/number with all four modifiers enabled.\n\n"
        out += "Output device: `\(config.outputDevice)` · volume \(Int(config.volume * 100))%\n\n"
        out += "| Key | Sends | Sound | File |\n|---|---|---|---|\n"
        for key in config.sortedKeys {
            let e = config.sounds[key]!
            out += "| `\(KeyCodes.label(key))` | Hyper+\(KeyCodes.label(key)) | \(e.displayName(key: key)) | `\(e.file)` |\n"
        }
        out += "| `\(KeyCodes.label(config.stopKey))` | Hyper+\(KeyCodes.label(config.stopKey)) | **Stop** | |\n"
        out += "\n_Generated by `soundboard map`._\n"
        return out
    }

    static func write(_ config: Config) throws {
        try markdown(config).write(to: Config.mapURL, atomically: true, encoding: .utf8)
    }
}
